- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.2  # Use the ref you want to point at
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-myst